# Generated by Django 4.0.1 on 2022-01-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSellsApp', '0002_item_rename_created_date_sells_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductSellsApp.item'),
        ),
    ]
