# Generated by Django 4.0.1 on 2022-01-11 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductSellsApp', '0003_alter_sells_item_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('user_name', 'item_name')},
        ),
    ]
